### Get all of the countries available for the app.
GET {{host}}/api/countries

### Add a new countryModel.
POST {{host}}/api/countries
Content-Type: application/json
X-CSRF-TOKEN: abcdefgh-abcd-abcd-abcd-abcdefghijkl

{
"countryCode":"FR",
"tax":15,
"fixedCosts":900,
"currencyCode":"EUR"
}

### Calculate salary.
GET {{host}}/api/salaries/pln?countryCode={{countryCode}}&salary={{salaryFromClient}}